name: sorting_stimulator_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.5.1
  google_fonts: ^5.0.0
  cupertino_icons: ^1.0.6
  animated_text_kit: ^4.2.1  # Add this line
  syncfusion_flutter_charts: ^26.1.42 # Add this line for flutter charts


dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: 1.25.2

flutter:
  uses-material-design: true

  assets:
    - assets/titlecard.mov
    - assets/logo.png
    - assets/sort.png
    - assets/search.png
    - assets/graph.png
